name: Deploy Infra via CDK

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, ec2]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: CDK Deploy
        run: cdk deploy --require-approval never
